### ISSUE TITLE
Community linter fails on extended communities

### ISSUE THREAD

**Issue by ewpratten** [NLNOG/lg.ring.nlnog.net#70]
Running the linter on the current `main` branch throws this error at the end:

```
Traceback (most recent call last):
  File "/home/ewpratten/projects/lg.ring.nlnog.net/communities/lint.py", line 88, in <module>
    check_communities()
  File "/home/ewpratten/projects/lg.ring.nlnog.net/communities/lint.py", line 70, in check_communities
    (warnings, lines) = check_communitydesc(filename)
  File "/home/ewpratten/projects/lg.ring.nlnog.net/communities/lint.py", line 39, in check_communitydesc
    if f"as{asn}.txt" != filename.split("/")[-1] and not is_private(asn):
  File "/home/ewpratten/projects/lg.ring.nlnog.net/communities/lint.py", line 15, in is_private
    asn = int(asn)
ValueError: invalid literal for int() with base 10: 'soo 201376'
```

**Comment by teunvink** [comment]
Thanks, it’s a thing I still need to fix after adding support for 
large and extended communities. I hope to find some time for it later 
this week.

Cheers,
Teun

**Comment by teunvink** [comment]
I've removed the linter for now, it's useless. Closing this ticket.
